version: "3"

services:
  solr:
    image: solr:8
    network_mode: "host"
    entrypoint:
      - bash
      - "-c"
      - "precreate-core topic; precreate-core motion_block; exec solr -f"
    # command:
    #   - solr-precreate
    #   - gettingstarted # core

  arangodb:
    image: arangodb:3.7
    environment:
      - ARANGO_NO_AUTH=1
    network_mode: "host"
