version: "3"

services:
  searchservice:
    image: search-service
    build:
      context: .
      dockerfile: dockerfile
    network_mode: "host"
    volumes:
      - ./:/app

  solr:
    image: solr:8
    network_mode: "host"
    entrypoint:
      - bash
      - "-c"
      - "precreate-core topic; precreate-core motion_block; exec solr -f"

  arangodb:
    image: arangodb:3.7
    environment:
      - ARANGO_NO_AUTH=1
    network_mode: "host"
